server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: lizard-backend
  profiles:
    active: dev
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lizard.lizardbackend.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

ali-oss:
  endpoint: ${ali-oss.endpoint}
  bucket-name: ${ali-oss.bucket-name}
  access-key-id: ${ali-oss.access-key-id}
  access-key-secret: ${ali-oss.access-key-secret}
