spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lizard
    username:
    password:

ali-oss:
  endpoint:
  bucket-name:
  access-key-id:
  access-key-secret: